export type VoiceAnalysis = {
  rawOutput?: string;
  chunkCount?: number | null;
  chunkMedianFake?: number | null;
  chunkMaxFake?: number | null;
  highChunkCount?: number | null;
  highChunkRatio?: number | null;
  alertBand?: 'none' | 'caution' | 'high';
};

export type FraudNotes = {
  matchCount: number;
  weightSum: number;
  comboBoost: number;
  negatedMatches: string[];
  urgencyHits: number;
  secrecyHits: number;
  impersonationHits: number;
  paymentAppHits: number;
  codeRequestHits: number;
  explicitScamHits: number;
  paymentRequestHits: number;
  hardBlockHits: number;
  threatHits: number;
  accountAccessHits: number;
  moneyAmountHits: number;
  taxScamHits: number;
  bankFraudHits: number;
  piiHarvestHits: number;
  giftCardHits: number;
  emailHits: number;
  linkHits: number;
  criticalKeywordHits: number;
  callbackHits: number;
  grandchildHits: number;
  sweepstakesHits: number;
  romanceHits: number;
  jobLoanHits: number;
  medicalScamHits: number;
  utilityHits: number;
  charityHits: number;
  familyEmergencyHits: number;
  governmentImpersonationHits: number;
  safePhraseMatches: string[];
  safePhraseDampening: number;
  repeatCallerBoost: number;
  callerHistory?: {
    windowDays: number;
    previousCalls: number;
  } | null;
  callerCountry?: string | null;
  callerRegion?: string | null;
  highRiskCountryBoost: number;
  timeOfDayBoost: number;
  durationBoost: number;
  repeatCallCount: number;
  detectedLocale?: string | null;
  localeBoost: number;
  regionMismatchBoost: number;
  commandSensitiveHits: number;
  actionBoost: number;
  techSupportHits: number;
  investmentHits: number;
  medicalHits: number;
  deviceHits: number;
  remoteAccessHits: number;
  voiceSyntheticScore: number | null;
  voiceBoost: number;
  voiceAnalysis?: VoiceAnalysis | null;
};
